---
- name: create dir
  file:
    path: $HOME/.kube/
    state: directory
    mode: '0755'
- name: Copy admin.conf to Home directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    mode: 0755
    owner: "ubuntu"
